Revert "Refactor bindings generation in GYP"
This reverts commit 12a220862704551c94aec4516bd62af71b4d3d6e.

Causes compilation issues on windows:

[181/7142 | 13.235] CXX obj\v8\src\runtime\v8_base.runtime-classes.obj
FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc
"E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe"
/nologo /showIncludes /FC
@obj\mojo\public\genmojopublicinterfaces\application\mojo_application_bindings.application.mojom.obj.rsp
/c genmojopublicinterfaces\application\application.mojom.cc
/Foobj\mojo\public\genmojopublicinterfaces\application\mojo_application_bindings.application.mojom.obj
/Fdobj\mojo\public\mojo_application_bindings.cc.pdb
c1xx : fatalerror C1083: Cannot open source file:
'genmojopublicinterfaces\application\application.mojom.cc': No such file
or directory
FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc
"E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe"
/nologo /showIncludes /FC
@obj\mojo\public\genmojopublicinterfaces\application\mojo_application_bindings.shell.mojom.obj.rsp
/c genmojopublicinterfaces\application\shell.mojom.cc
/Foobj\mojo\public\genmojopublicinterfaces\application\mojo_application_bindings.shell.mojom.obj
/Fdobj\mojo\public\mojo_application_bindings.cc.pdb
c1xx : fatalerror C1083: Cannot open source file:
'genmojopublicinterfaces\application\shell.mojom.cc': No such file or
directory
FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc
"E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe"
/nologo /showIncludes /FC
@obj\mojo\public\genmojopublicinterfaces\application\mojo_application_bindings.service_provider.mojom.obj.rsp
/c genmojopublicinterfaces\application\service_provider.mojom.cc
/Foobj\mojo\public\genmojopublicinterfaces\application\mojo_application_bindings.service_provider.mojom.obj
/Fdobj\mojo\public\mojo_application_bindings.cc.pdb
c1xx : fatalerror C1083: Cannot open source file:
'genmojopublicinterfaces\application\service_provider.mojom.cc': No such
file or directory
ninja: build stopped: subcommand failed.

TBR=ncbray@chromium.org

Review URL: https://codereview.chromium.org/694023002

Cr-Mirrored-From: https://github.com/domokit/mojo
Cr-Mirrored-Commit: 91d94d6993c9b0c4135a95687a7d541ce90629b7